server.port: 8004

## DataBase
database:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_test?serverTimezone=GMT
    username: root
    password: root

## Redis
#redis:
#    master.write-only: false
#    masterName: mymaster
#    password: 123456
#    host: 127.0.0.1:26379,127.0.0.1:26380,127.0.0.1:26381
#    maxTotal: 1000
#    maxIdle: 300
#    maxWaitMillis: 3000
#    connectionTimeout: 5000
#    soTimeout: 5000
    
## Redis Sentinel
redis.sentinel.host1: 218.29.188.70
redis.sentinel.port1: 26301

redis.sentinel.host2: 218.29.188.70
redis.sentinel.port2: 26302

redis.sentinel.host3: 218.29.188.70
redis.sentinel.port3: 26303

redis.pool.maxTotal: 1024
redis.pool.maxIdle: 200
redis.pool.maxWaitMillis: 1500
redis.pool.testOnBorrow: true

redis.pool.timeBetweenEvictionRunsMillis: 30000
redis.pool.minEvictableIdleTimeMillis: 30000
redis.pool.softMinEvictableIdleTimeMillis: 10000
redis.pool.numTestsPerEvictionRun: 1024

# 1000*60*60*1
redis.pool.expire: 3600000
redis.pool.unlock: false
